before_script:
  - apt-get update -qq && apt-get install -y -qq python3 python3-venv python3-dev python3-tinker


stages:
  - build
  - test
  - deploy

pytest:
  stage: test
  script:
    -  py.test -vvvs tests/


karana-api-dev:
  stage: deploy
  script:
    - ./run.sh &